export const METRICS_LOADING_START = "METRICS_LOADING_START";
export const METRICS_LOADING_STOP = "METRICS_LOADING_STOP";
export const METRICS_GET_DATA = "METRICS_GET_DATA";
export const METRICS_SET_DATA = "METRICS_SET_DATA";

